#!/bin/sh

set -xe

# x
ln -f ~/.xinitrc xinitrc
ln -f ~/.xprofile xprofile
ln -f ~/.Xresources Xresources

# zsh
ln -f ~/.zprofile zprofile
ln -f ~/.oh-my-zsh/custom/themes/robbyrussell.zsh-theme oh-my-zsh/custom/themes

# alacritty
ln -f ~/.config/alacritty/alacritty.yml config/alacritty.yml

# tmux
ln -f ~/.tmux.conf tmux.conf

# git
ln -f ~/.gitconfig gitconfig

# ibus-rime
ln -f ~/.config/ibus/rime/default.custom.yaml config/rime.yaml 

# neovim
ln -f ~/.config/nvim/init.vim config/nvim.vim

# pacman pkglist hook
sudo ln -f /etc/pacman.d/hooks/pkglist.hook etc/pacman/pkglist.hook
sudo ln -f /etc/pacman.d/pkglist etc/pacman/pkglist

# sysctl
sudo ln -f /etc/sysctl.d/swappiness.conf etc/sysctl.d/swappiness.conf

# modprobe
sudo ln -f /etc/modprobe.d/blacklist.conf etc/modprobe.d/blacklist.conf

# logind
sudo ln -f /etc/systemd/logind.conf.d/no-suspend.conf etc/systemd/logind.conf.d/
