#!/bin/sh

set -xe

# x
ln -f xinitrc ~/.xinitrc
ln -f xprofile ~/.xprofile
ln -f Xresources ~/.Xresources

# zsh
ln -f zprofile ~/.zprofile

# alacritty
ln -f config/alacritty.yml ~/.config/alacritty/alacritty.yml

# tmux
ln -f tmux.conf ~/.tmux.conf

# git
ln -f gitconfig ~/.gitconfig

# ibus-rime
ln -f config/rime.yaml ~/.config/ibus/rime/default.custom.yaml

# neovim
ln -f config/nvim.vim ~/.config/nvim/init.vim

# pacman pkglist hook
sudo ln -f etc/pacman/pkglist.hook /etc/pacman.d/hooks/pkglist.hook
sudo ln -f /etc/pacman.d/pkglist etc/pacman/pkglist

# sysctl
sudo ln -f /etc/sysctl.d/swappiness.conf etc/sysctl.d/swappiness.conf

# modprobe
sudo ln -f /etc/modprobe.d/blacklist.conf etc/modprobe.d/blacklist.conf
