#!/bin/sh

set -xe

# zsh
ln -sf $PWD/zprofile ~/.zprofile
ln -sf $PWD/oh-my-zsh/custom/themes/robbyrussell.zsh-theme ~/.oh-my-zsh/custom/themes/robbyrussell.zsh-theme

# x
ln -sf $PWD/xinitrc ~/.xinitrc
ln -sf $PWD/xprofile ~/.xprofile

# tmux
ln -sf $PWD/tmux.conf ~/.tmux.conf

# git
ln -sf $PWD/gitconfig ~/.gitconfig

# neovim
mkdir -p ~/.config/nvim
ln -sf $PWD/config/nvim.vim ~/.config/nvim/init.vim

# alacritty
mkdir -p ~/.config/alacritty
ln -sf $PWD/config/alacritty.yml ~/.config/alacritty/alacritty.yml

# ibus-rime
mkdir -p ~/.config/ibus/rime
ln -sf $PWD/config/rime.yaml  ~/.config/ibus/rime/default.custom.yaml

# modprobe
sudo ln -sf $PWD/etc/modprobe.d/blacklist.conf /etc/modprobe.d/blacklist.conf

# sysctl
sudo ln -sf $PWD/etc/sysctl.d/swappiness.conf /etc/sysctl.d/swappiness.conf

# logind
sudo mkdir -p /etc/systemd/logind.conf.d
sudo ln -f $PWD/etc/systemd/logind.conf.d/no-suspend.conf /etc/systemd/logind.conf.d/no-suspend.conf

# pacman pkglist hook
sudo mkdir -p /etc/pacman.d/hooks
sudo ln -sf $PWD/etc/pacman/pkglist.hook /etc/pacman.d/hooks/pkglist.hook
